version: '3.9'
services:
  postgres:
    env_file:
      - ./.env
    image: 'postgres'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=glerystonmatos
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '54320:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'glerystonmatos@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - postgres_net

networks:
  postgres_net:
    name: postgres_net